name: analise_env
channels:
- defaults
dependencies:
- python=3.12
- ipykernel
- pandas
- matplotlib
- statsmodels
- jupyterlab
- notebook
- scikit-learn
- textblob
- nltk
- wordcloud
- spacy
- pip
- pip:
  - ace_tools
